version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=TamDaoStay_123
    ports:
      - "1433:1433"
    networks:
      - db_net
  sqlcmd:
    image: mcr.microsoft.com/mssql-tools:latest
    command:
      - /bin/bash
      - -c
      - |
        # Chờ SQL Server sẵn sàng
        until /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P TamDaoStay_123 -Q 'SELECT 1' > /dev/null 2>&1; do
          echo 'Waiting for SQL Server to be available...'
          sleep 5
        done
        # Thực thi các script SQL
        /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P TamDaoStay_123 -d master -i /opt/mssql_scripts/EXE202.sql
    stdin_open: true
    volumes:
      - ./sqlscripts:/opt/mssql_scripts
    networks:
      - db_net
  app:
    image: ocean_booking
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=TamDaoStay_DB;User Id=sa;Password=TamDaoStay_123;TrustServerCertificate=True
    depends_on:
      - sqlserver
    networks:
      - db_net
networks:
  db_net:
    name: db_net

